# -*- coding: utf-8 -*-
# This file is automatically generated by Containers Testing Framework
# Any changes to this file will be discarded


# Some useful functions for your environment.py
def before_scenario(context, scenario):
    context.containers = []
    context.variables = {}


def after_scenario(context, scenario):
    try:
        for container in context.containers:
            container.stop()

        context.containers = []
    except AttributeError:
        pass
